// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJKL5QpO49A5HrLg3SBA4PklHtv3xelg',
    appId: '1:776825925535:web:633cde0736f428d3cb57aa',
    messagingSenderId: '776825925535',
    projectId: 'sami-food-5c155',
    authDomain: 'sami-food-5c155.firebaseapp.com',
    storageBucket: 'sami-food-5c155.firebasestorage.app',
    measurementId: 'G-NQL0W628T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23kTbu10iJ8_pq6oyJ6hw_pxD0xIkBgo',
    appId: '1:776825925535:android:62bc4b33ff66453ccb57aa',
    messagingSenderId: '776825925535',
    projectId: 'sami-food-5c155',
    storageBucket: 'sami-food-5c155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDG8Gpu3by1RpBycO5R-5z5S2sf_M8XM',
    appId: '1:776825925535:ios:9d42eae4d8424db3cb57aa',
    messagingSenderId: '776825925535',
    projectId: 'sami-food-5c155',
    storageBucket: 'sami-food-5c155.firebasestorage.app',
    iosClientId: '776825925535-oljgj54r119mrp9l5cubug8gserj4lpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.customerApp',
  );
}
